# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spider_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SPIDER(object):
    def setupUi(self, SPIDER):
        SPIDER.setObjectName("SPIDER")
        SPIDER.resize(521, 290)
        self.centralwidget = QtWidgets.QWidget(SPIDER)
        self.centralwidget.setObjectName("centralwidget")
        self.GUI_label = QtWidgets.QLabel(self.centralwidget)
        self.GUI_label.setGeometry(QtCore.QRect(0, 0, 521, 281))
        self.GUI_label.setText("")
        self.GUI_label.setPixmap(QtGui.QPixmap("Jarvis_Gui (1).gif"))
        self.GUI_label.setScaledContents(True)
        self.GUI_label.setObjectName("GUI_label")
        SPIDER.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SPIDER)
        self.statusbar.setObjectName("statusbar")
        SPIDER.setStatusBar(self.statusbar)

        self.retranslateUi(SPIDER)
        QtCore.QMetaObject.connectSlotsByName(SPIDER)

    def retranslateUi(self, SPIDER):
        _translate = QtCore.QCoreApplication.translate
        SPIDER.setWindowTitle(_translate("SPIDER", "SPIDER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SPIDER = QtWidgets.QMainWindow()
    ui = Ui_SPIDER()
    ui.setupUi(SPIDER)
    SPIDER.show()
    sys.exit(app.exec_())
